version: "3.9" #docker compose version
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=giftly
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "1306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 20
  web:
    build: .
    entrypoint:
      - sh #says to use shell script
      - -c #tells shell to execute next command
      - |
        python manage.py migrate
        if ! python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); exit(not User.objects.filter(username='admin').exists())"; then
          python manage.py createsuperuser --username admin --no-input
        fi
        python manage.py runserver 0.0.0.0:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_EMAIL=admin@giftly.ee #superuser username by default is admin, both should work
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
volumes:
  dbdata:

